### ISSUE TITLE
How to use your library? 

### ISSUE THREAD

**Issue by worddevfr** [emersion/go-msgauth#1]
Hi, How to use your library? Can you give us a concrete example with the domain gmail.com?

**NB: It is not issue**

**Comment by emersion** [comment]
Read the README. Read the docs.

**Comment by emersion** [comment]
Oh, and read the RFC too.

**Comment by worddevfr** [comment]
read me is empty and no doc. It's nothing, I'm going to look for another bookstore. Good continuation

**Comment by emersion** [comment]
Oh, sorry. I though this issue was for go-imap.

Then read the docs: https://godoc.org/github.com/emersion/go-msgauth

I should add an example to README. Will do tomorrow.

**Comment by emersion** [comment]
Updated README with an example usage.

**Comment by worddevfr** [comment]
>go build
# spf
.\main.go:12:29: undefined: ResultPass
.\main.go:13:30: undefined: ResultPass

in main.go

package main

import (
	"github.com/emersion/go-msgauth"
	"log"
)

func main() {

	// Format
	results := []msgauth.Result{
		&msgauth.SPFResult{Value: ResultPass, From: "example.net"},
		&msgauth.AuthResult{Value: ResultPass, Auth: "sender@example.com"},
	}

	s := msgauth.Format("example.com", results)
	log.Println(s)

	// Parse
	identifier, results, err := msgauth.Parse(s)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(identifier, results)
}

**Comment by emersion** [comment]
Fixed.
