### ISSUE TITLE
dkim: export isFail

### ISSUE THREAD

**Issue by mschneider82** [emersion/go-msgauth#22]
Hi,

It would be nice to have the private function dkim.isFail() public available. In case of a "bad signature (body hash mismatched; bh=)" dkim.IsPermfail() and dkim.IsTempfail() returns false.

Thanks
Matthias

**Comment by emersion** [comment]
If dkim.IsPermfail() and dkim.IsTempfail() both return false, then the error will verify dkim.isFail(). Why would you need this function?

**Comment by emersion** [comment]
Ref https://github.com/emersion/go-msgauth/blob/3bd269157ff3da507527a94fcd0756e76e4b0e90/cmd/dkim-milter/main.go#L275
