### ISSUE TITLE
Getting error on importing this project

### ISSUE THREAD

**Issue by rishabh625** [emersion/go-msgauth#28]
Error : 
module github.com/emersion/go-msgauth@latest found (v0.4.0), but does not contain package github.com/emersion/go-msgauth

As the code in master is not tagged

**Comment by emersion** [comment]
Not sure what this is about

**Comment by rishabh625** [comment]
Code has been directly updated in master branch and not tagged, v 0,4.0 have 6 months old code , while there has been changes done in master branch .

**Comment by emersion** [comment]
Is this a request for a new release?

**Comment by rishabh625** [comment]
1) Yes and 
Can u pls help me in using this as library
my go.mod looks like this

go 1.14

require (
        github.com/emersion/go-msgauth v0.4.0
        github.com/go-kit/kit v0.10.0
        github.com/golang/protobuf v1.4.1
        github.com/prometheus/client_golang v1.3.0
        github.com/sirupsen/logrus v1.6.0
        golang.org/x/net v0.0.0-20200506145744-7e3656a0809f
        google.golang.org/grpc v1.29.1
        google.golang.org/protobuf v1.22.0
)

on running go build this library is giving error
Error :
module github.com/emersion/go-msgauth@latest found (v0.4.0), but does not contain package github.com/emersion/go-msgauth

**Comment by rishabh625** [comment]
package main

import(
        "github.com/emersion/go-msgauth"
        "log"
)

func main(){
        test := Sign("Mail","domain.com","selector","key")
        fmt.Println(test)
}

func Sign(mail,domain,selector,privatekey) (string signedMail){
        r := strings.NewReader(mailString)
        options := &dkim.SignOptions{
                Domain: domain,
                Selector: selector,
                Signer: privatekey,
        }
        var b bytes.Buffer
        if err := dkim.Sign(&b, r, options); err != nil {
                log.Fatal(err)
        }
        return b.String()
}


This sample code with go mod as dependency manager doesn't work
Gives import error

**Comment by foxcpp** [comment]
`"github.com/emersion/go-msgauth"` package does not exist, repository root has no Go files. You need to import `"github.com/emersion/go-msgauth/dkim"`.

**Comment by rishabh625** [comment]
Yeah got it Thanks
