### ISSUE TITLE
FR: dkim-milter config file

### ISSUE THREAD

**Issue by mimi89999** [emersion/go-msgauth#52]
Hello,
I would like `dkim-milter` to read config from a file. If you accept this feature, I could contribute it.

**Comment by emersion** [comment]
I'd rather not tbh. `dkim-milter` is designed to be pretty bare-bones.

**Comment by mimi89999** [comment]
I think that it would be best to have all email auth handled by one milter to avoid issues like https://github.com/trusteddomainproject/OpenDMARC/issues/49 and make configuration easier.

**Comment by emersion** [comment]
Yes, I agree. But as the name suggests `dkim-milter` is only about DKIM.

I think a separate project would be nice for a proper SPF+DKIM+DMARC milter. We may want to improve go-milter, it's quite fragile atm.

In any case, this isn't a go-msgauth issue, closing.
