### ISSUE TITLE
dmarc.Lookup() merges multiple TXT records into a single string

### ISSUE THREAD

**Issue by wttw** [emersion/go-msgauth#57]
net.LookupTXT() returns a slice of strings, with one string for each TXT resource record returned. If there are multiple strings inside a TXT record it concatenates those before returning it.

dmarc.LookupWithOptions then concatenates all of those TXT resource records into a single string before parsing it.

If there are multiple TXT records for _dmarc.example.com it'll likely give the wrong response. That's not going to happen in
a healthy DNS zone, but it happens occasionally.

I think that correct behaviour would be for dmarc.LookupWithOptions to remove any TXT records that don't start with "v=", then return an error if there are more than one, then parse just the first remaining TXT RR, if any.

**Comment by emersion** [comment]
[Section 6.6.3](https://datatracker.ietf.org/doc/html/rfc7489#section-6.6.3) says that we should indeed ignore TXT records that do not start with `v=`.

**Comment by emersion** [comment]
This actually causes more issues: https://github.com/emersion/go-msgauth/issues/62
