### ISSUE TITLE
Dkim milter is not working

### ISSUE THREAD

**Issue by abolinhas** [emersion/go-msgauth#66]
Hi
I'm testing you dkim milter
https://github.com/emersion/go-msgauth/tree/master/cmd/dkim-milter

But seems is not working, at least the message is not been signed.
I have tried to catch any error / panic but aparently is working.
What I could find was this:

1. When I print the **dkim.SignOptions** this is the output
`{domain.tld default  0xc0003f2180 unknown hash value 0   [From To] 0001-01-01 00:00:00 +0000 UTC []}`
**unknown hash value** and **empty map[]** ?

2. When I print the **s.signer, err = dkim.NewSigner(&opts)** this is the output
`&{0xc00039ef60 0xc0003a6d90 map[]}`
**empty map[]** ?

3. **s.verifs, err = dkim.VerifyWithOptions(pr, &options)** always return empty map **[]**

Can you help me to solve this issue please

**Comment by emersion** [comment]
You need to provide a key for messages to be signed.

**Comment by abolinhas** [comment]
Both key and domain are present
This is what i get on hotmail
Authentication-Results: spf=none (sender IP is XX.XX.XX.XX)
 smtp.mailfrom=domain.tld; dkim=fail (signature did not verify)
 header.d=domain.tld;dmarc=none action=none
 header.from=domain.tld;compauth=pass reason=105

DKIM-Signature: a=rsa-sha256; bh=7LvgXbfN3+/NB8QhHYaXc3Ek0sm4m0IPa9++RJTItKE=;
 c=simple/simple; d=domain.tld; h=Date:From:To:Subject; q=dns/txt;
 s=default; t=1728983676; v=1;
 b=DxTZ00ZJZKjXV+oO2ie7E83s/GuyfrqqnEGyo0CpgoVehTN85yStqML0jO7CDicrVhaufS1q
 39NFT35WX5WjsogeP6ejm5sgOjF8sdDPkT2oj72QsIjafcwaiQ5BZSH/819YNIhUvDkShJPY/sI
 8CZOmIwinicgvvw8VCnwCKT0F9GnsBGwZHLzwRtr79+5MMp1vekp7+RYt+kHopVstz1+NVOtPgB
 uUV0BJSaC98MVW3IEDinxr6bhcUnKnx09sJSU4vxcRCosAawiLYWzJSmmNo2qetH7jLMYYJgggk
 EOwWOHjrHKGdSKuq9z+cUFuvKxwh+86ICTUew2qkqr+54RSdMqQYx2mg2DAZ6kjt4R0ZApP42yo
 gasAES2tqMX61GfbNOFE8JD3itxYZaLu3XS5+gytYthAr7G3Wpr1BLPgyXoSrgS1tU4c7Z0QfbM
 PcyiqSlaNeCt41klCXn9XPSLVQH+YNuTR9Lg6MAIQI8xWOcPR47k2sleXhj7Y/u4sLTTMxGoEGM
 9Nj+p6qXA3Emgt0vBOb5P5zXC2UkKBeB/gaMfcMsPNfDNbI8X5tPUPBdUJWQY/UXWveLcUI1/sG
 rPJ8taFf8sFkuuiTIZdDjbhdpVy5G7J2jPAfxGsLAiyNNDxrJhjmVaFfEXU4zZs4zj1tXLVSeZj
 UlaaPZZJGqo=

**Comment by abolinhas** [comment]
New output:
**Start signing the message:**
dkimDomain domain.tld
dkimSelector default
dkimCanonicalization simple/relaxed
dkimSelector default
dkimCanonicalization simple/relaxed
dkimDomain domain.tld

**loadPrivateKey() output**
```
PRIVATE KEY
&{{764143902614281448402886165076606649777883163905896930189123913172337543262614247418822385904312705180898343599809133232434912908412284615352841437010642511783322922647397951779815803913519935674456470182497610860088042459345992517637914092364940843205034437592628893600010571905241481493633889882166518995246895806878960661640284673671503780369258932107859441771827975028375706145215444652079312334050659693130877234568603949072069000474833976551704213118624304498594765677811544784741424611810789846847503570489657433690168315204000929951346752220514675387749403926857015895770152878906450894237525015568382387729470666997834269260560883996240251355946742373885143801061333338279254711647323502911362330064802472867970254081215138259604507489377488073863022607619049010323470228604909358316984349211352019421031808228011878027054631196298784025195188346924890473987444717344462360540492218680308756502164532790083100237945927169192471140921151059573728053602992559434112313001634185534823391060884196370644428804990551806692573562988347358804895376300704195604215680965679927236949614706561521043207903969518128731407365562542040744776411272311043158038570479992627122610716097471344982543534796997770593728425440647734689992228577 65537} 708398720527843564386007169162371082196393937871228067970313143242726090276689369610723299479720199520433644563376469760132681823450825702891149035613754008360278430327377053547377649000866948621958241945890486983162322163968828622024339054209444220360484494108332103385297500750337236212021005137264583793509321477070023558579384708387412967943523439875873296676521361228374725766493882162468997667997953527257268066335811854827389477590506325882712684014146791035851863581200210796065581178802452781406944579835354487408332181188249088303157350472398639209272667119033902341630093051418898187745778260309026051679026505577891654498224397282734112675813058776547858316379548065837688921315247109670223971475449636551981501227669971036520008569045725864239156866877219749098917353099186795235309092824671164613484047756004599267821439792906527284008869159488595396044300191726367985418722248683788167062178230714491811355117339081903319930252149135678874127726276245928468952661638253601956039961636217071248342895274907329429823680198316897656936049856781936934197615626208858740319247930859151338012241993144294088851252176129929524964342739015188139410368926250984427622809510326935300592565634419902296256164460786103774933589761 [27056333609686166374618880520141109254746899320764674794522221833310817061221005415047858094757232270960428922620715973691640135491296879873216201736145233822662627566407669431001544133800912955094407674866883746310979980067785090290160845902398447673279357723683083641425668539821396756421040568462639179571324536050622608991546590220508881488439798046025146814698847577396532153319786777722624059076910053274408603748268832655243391018196097238743738549144423998289470166639377904804562833858750473941463253493925680516736491196429814202395821864697143053569916981492067365095172885697004308435509741213560686642569 28242699607337705251306844626793661749595826157357754211928609519802956469087719919491303581959408239593082022808542836633589560918422809556308091567735715787532425416976160554024611377332624089317740967502861450813871446204745089818299307833274887750808626702697463409258135959345989267865180510256153981208149090928768699996378155820623647247922859330445620486333155023866502877447997087187348094263901782899329707920750484116887848415961291451644351144976316075839969550707642492552588888890374345077915709090461642744299672699997748791449061977578303457401844485238411344497725649746629288640759359038031375790233] {5993206814651480495908300479284808322797209781337882173307888587426539684113483003650605855647813309695783247168545001908563709765890364299853206594803246401324341431276075150370774008428641124389360456170446485881204455050491114267394982986177552601934730550295364835475783606094072305918248408263608846450660211633838723388777054949587674635208821707343135271815663980363236908460004953723840478899240173388842786526902644973925695521783919673083034812669630944095217028687670309047527940844522645684242825441679037857415866498292134409206709889219958583833170343780159939257009395939139898767998152390211033278761 25515262498302498627025583359982897063797086762055600826706579679394745664613054015185942329991495537632592282320646417617552996366296560846695599211781074207672304867301288037027773478021728292114756659656521061076761227808574504142116139252522079954069871520107899561093057568716256962811260931248704776223691828672513804253865112071463217819781446438454984173135991007416999593633230259825571905414912137600187883891111809567003306971821049853807143180062525324905517755745580308818738772501354719065157595004776735944649511287081598340542228993827245542302034091917479574668070559686870423147871891144296530170561 16075158107571272486639459137417700712398497501619781282110741005735896556123353211186954671224335215948730072954355426189292558316198566488681563862177292699367608894662546855714984250899029242651036178296410986171166013358609124239623110320648554369913331632550244923187452081591179292052189108169615045202363501837383178761223637416276368915168453759574985501388807484152116491933730249197845443421829917265554666376686526317761842705142059024335703494312692883321976637374264393019693176544570125280897342852533453782282987658108077101626810471323367895152307123020792405167979342833028941937620751688921329933369 [] 0xc0004d8880 0xc0004d88a0 0xc0004d88c0}}
```

**dkim.SignOptions output:**
```
opts := dkim.SignOptions{
				Domain:       s.signDomain,
				Selector:     Options.Selector,
				Hash:         crypto.SHA256,
				Signer:       privateKey,
				HeaderKeys:   s.signHeaderKeys,
				QueryMethods: []dkim.QueryMethod{dkim.QueryMethodDNSTXT},
			}
fmt.Printf("%+v\n", opts)
{Domain:domain.tld Selector:default Identifier: Signer:0xc0004db700 Hash:SHA-256 HeaderCanonicalization: BodyCanonicalization: HeaderKeys:[Date From To Subject] Expiration:0001-01-01 00:00:00 +0000 UTC QueryMethods:[dns/txt]}
```

**dkim.NewSigner() output:**
```
s.signer, err = dkim.NewSigner(&opts)
fmt.Printf("%+v\n", s.signer)
&{pw:0xc00038cde0 done:0xc000380cb0 sigParams:map[]}
```

But still getting errors on hotmail, gmail..
**Hotmail:**
Authentication-Results: spf=none (sender IP is XX.XX.XX.XX)
smtp.mailfrom=domain.tld; dkim=fail (signature did not verify)
header.d=domain.tld;dmarc=none action=none
header.from=domain.tld;compauth=pass reason=105

DKIM-Signature: a=rsa-sha256; bh=7LvgXbfN3+/NB8QhHYaXc3Ek0sm4m0IPa9++RJTItKE=;
c=simple/simple; d=domain.tld; h=Date:From:To:Subject; q=dns/txt;
s=default; t=1728983676; v=1;
b=DxTZ00ZJZKjXV+oO2ie7E83s/GuyfrqqnEGyo0CpgoVehTN85yStqML0jO7CDicrVhaufS1q
39NFT35WX5WjsogeP6ejm5sgOjF8sdDPkT2oj72QsIjafcwaiQ5BZSH/819YNIhUvDkShJPY/sI
8CZOmIwinicgvvw8VCnwCKT0F9GnsBGwZHLzwRtr79+5MMp1vekp7+RYt+kHopVstz1+NVOtPgB
uUV0BJSaC98MVW3IEDinxr6bhcUnKnx09sJSU4vxcRCosAawiLYWzJSmmNo2qetH7jLMYYJgggk
EOwWOHjrHKGdSKuq9z+cUFuvKxwh+86ICTUew2qkqr+54RSdMqQYx2mg2DAZ6kjt4R0ZApP42yo
gasAES2tqMX61GfbNOFE8JD3itxYZaLu3XS5+gytYthAr7G3Wpr1BLPgyXoSrgS1tU4c7Z0QfbM
PcyiqSlaNeCt41klCXn9XPSLVQH+YNuTR9Lg6MAIQI8xWOcPR47k2sleXhj7Y/u4sLTTMxGoEGM
9Nj+p6qXA3Emgt0vBOb5P5zXC2UkKBeB/gaMfcMsPNfDNbI8X5tPUPBdUJWQY/UXWveLcUI1/sG
rPJ8taFf8sFkuuiTIZdDjbhdpVy5G7J2jPAfxGsLAiyNNDxrJhjmVaFfEXU4zZs4zj1tXLVSeZj
UlaaPZZJGqo=

**Gmail:**
<x@gmail.com>: host gmail-smtp-in.l.google.com[74.125.206.26]
    said: 550-5.7.26 Your email has been blocked because the sender is
    unauthenticated. 550-5.7.26 Gmail requires all senders to authenticate with
    either SPF or DKIM. 550-5.7.26  550-5.7.26  Authentication results:
    550-5.7.26  DKIM = did not pass 550-5.7.26  SPF [domain.tld] with ip:
    [37.187.142.164] = did not pass 550-5.7.26  550-5.7.26  For instructions on
    setting up authentication, go to 550 5.7.26
    https://support.google.com/mail/answer/81126#authentication
    ffacd0b85a97d-37d7fbebeb4si510465f8f.66 - gsmtp (in reply to end of DATA
    command)


Reporting-MTA: dns; ns413437.ip-37-187-142.eu
X-Postfix-Queue-ID: 86F526B624
X-Postfix-Sender: rfc822; dkimtest@domain.tld
Arrival-Date: Tue, 15 Oct 2024 11:40:58 +0200 (CEST)

Final-Recipient: rfc822; x@gmail.com
Original-Recipient: rfc822;x@gmail.com
Action: failed
Status: 5.7.26
Remote-MTA: dns; gmail-smtp-in.l.google.com
Diagnostic-Code: smtp; 550-5.7.26 Your email has been blocked because the
    sender is unauthenticated. 550-5.7.26 Gmail requires all senders to
    authenticate with either SPF or DKIM. 550-5.7.26  550-5.7.26
    Authentication results: 550-5.7.26  DKIM = did not pass 550-5.7.26  SPF
    [domain.tld] with ip: [37.187.142.164] = did not pass 550-5.7.26
    550-5.7.26  For instructions on setting up authentication, go to 550 5.7.26
    https://support.google.com/mail/answer/81126#authentication
    ffacd0b85a97d-37d7fbebeb4si510465f8f.66 - gsmtp

please help

**Comment by abolinhas** [comment]
Ok fixed, typo issue on my code.
Thanks for your help
